// This file is auto-generated by @analogjs/platform
// Do not edit manually

import type { Graph, Thing, WithContext } from 'schema-dts';
import * as routeModule0 from './app/pages/docs.page';
import * as routeModule1 from './app/pages/docs/[[...slug]].page';

declare module '@analogjs/router' {
  interface AnalogRouteTable {
    '/': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/contributing': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/contributors': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/features/api/og-image-generation': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/features/api/overview': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/features/api/websockets': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/features/data-fetching/overview': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/features/data-fetching/server-side-data-fetching': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/features/data-fetching/validation': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/features/deployment/overview': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/features/deployment/providers': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/features/generation/code-generation': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/features/routing/content': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/features/routing/metadata': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/features/routing/middleware': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/features/routing/overview': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/features/routing/typed-routes': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/features/server/server-side-rendering': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/features/server/static-site-generation': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/features/testing/overview': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/features/testing/vitest': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/features/updating/overview': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/getting-started': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/guides/compatibility': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/guides/forms': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/guides/libraries': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/guides/migrating': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/integrations/angular-material': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/integrations/ionic': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/integrations/nx': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/integrations/storybook': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/integrations/tanstack-query': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/introduction': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/packages/astro-angular/overview': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/packages/create-analog/overview': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/packages/router/overview': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/packages/vite-plugin-angular/css-preprocessors': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/packages/vite-plugin-angular/overview': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/packages/vite-plugin-nitro/overview': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/sponsoring': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/support': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/[[...slug]]': {
      params: { slug?: string[] };
      paramsOutput: { slug?: string[] };
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
  }
}

export {};

export interface AnalogGeneratedRouteRecord<
  TId extends string = string,
  TPath extends string = string,
  TFullPath extends string = string,
  TParentId extends string | null = string | null,
  TChildren extends readonly string[] = readonly string[],
> {
  id: TId;
  path: TPath;
  fullPath: TFullPath;
  parentId: TParentId;
  children: TChildren;
  sourceFile: string;
  kind: 'page' | 'content';
  hasParamsSchema: boolean;
  hasQuerySchema: boolean;
  hasJsonLd: boolean;
  isIndex: boolean;
  isGroup: boolean;
  isCatchAll: boolean;
  isOptionalCatchAll: boolean;
}

export interface AnalogFileRoutesById {
  "/index": AnalogGeneratedRouteRecord<"/index", "/", "/", null, readonly []>;
  "/docs": AnalogGeneratedRouteRecord<"/docs", "docs", "/docs", null, readonly ["/docs/contributing", "/docs/contributors", "/docs/features/api/og-image-generation", "/docs/features/api/overview", "/docs/features/api/websockets", "/docs/features/data-fetching/overview", "/docs/features/data-fetching/server-side-data-fetching", "/docs/features/data-fetching/validation", "/docs/features/deployment/overview", "/docs/features/deployment/providers", "/docs/features/generation/code-generation", "/docs/features/routing/content", "/docs/features/routing/metadata", "/docs/features/routing/middleware", "/docs/features/routing/overview", "/docs/features/routing/typed-routes", "/docs/features/server/server-side-rendering", "/docs/features/server/static-site-generation", "/docs/features/testing/overview", "/docs/features/testing/vitest", "/docs/features/updating/overview", "/docs/getting-started", "/docs/guides/compatibility", "/docs/guides/forms", "/docs/guides/libraries", "/docs/guides/migrating", "/docs/integrations/angular-material/index", "/docs/integrations/ionic/index", "/docs/integrations/nx/index", "/docs/integrations/storybook/index", "/docs/integrations/tanstack-query/index", "/docs/introduction", "/docs/packages/astro-angular/overview", "/docs/packages/create-analog/overview", "/docs/packages/router/overview", "/docs/packages/vite-plugin-angular/css-preprocessors", "/docs/packages/vite-plugin-angular/overview", "/docs/packages/vite-plugin-nitro/overview", "/docs/sponsoring", "/docs/support", "/docs/[[...slug]]"]>;
  "/docs/contributing": AnalogGeneratedRouteRecord<"/docs/contributing", "contributing", "/docs/contributing", "/docs", readonly []>;
  "/docs/contributors": AnalogGeneratedRouteRecord<"/docs/contributors", "contributors", "/docs/contributors", "/docs", readonly []>;
  "/docs/features/api/og-image-generation": AnalogGeneratedRouteRecord<"/docs/features/api/og-image-generation", "features/api/og-image-generation", "/docs/features/api/og-image-generation", "/docs", readonly []>;
  "/docs/features/api/overview": AnalogGeneratedRouteRecord<"/docs/features/api/overview", "features/api/overview", "/docs/features/api/overview", "/docs", readonly []>;
  "/docs/features/api/websockets": AnalogGeneratedRouteRecord<"/docs/features/api/websockets", "features/api/websockets", "/docs/features/api/websockets", "/docs", readonly []>;
  "/docs/features/data-fetching/overview": AnalogGeneratedRouteRecord<"/docs/features/data-fetching/overview", "features/data-fetching/overview", "/docs/features/data-fetching/overview", "/docs", readonly []>;
  "/docs/features/data-fetching/server-side-data-fetching": AnalogGeneratedRouteRecord<"/docs/features/data-fetching/server-side-data-fetching", "features/data-fetching/server-side-data-fetching", "/docs/features/data-fetching/server-side-data-fetching", "/docs", readonly []>;
  "/docs/features/data-fetching/validation": AnalogGeneratedRouteRecord<"/docs/features/data-fetching/validation", "features/data-fetching/validation", "/docs/features/data-fetching/validation", "/docs", readonly []>;
  "/docs/features/deployment/overview": AnalogGeneratedRouteRecord<"/docs/features/deployment/overview", "features/deployment/overview", "/docs/features/deployment/overview", "/docs", readonly []>;
  "/docs/features/deployment/providers": AnalogGeneratedRouteRecord<"/docs/features/deployment/providers", "features/deployment/providers", "/docs/features/deployment/providers", "/docs", readonly []>;
  "/docs/features/generation/code-generation": AnalogGeneratedRouteRecord<"/docs/features/generation/code-generation", "features/generation/code-generation", "/docs/features/generation/code-generation", "/docs", readonly []>;
  "/docs/features/routing/content": AnalogGeneratedRouteRecord<"/docs/features/routing/content", "features/routing/content", "/docs/features/routing/content", "/docs", readonly []>;
  "/docs/features/routing/metadata": AnalogGeneratedRouteRecord<"/docs/features/routing/metadata", "features/routing/metadata", "/docs/features/routing/metadata", "/docs", readonly []>;
  "/docs/features/routing/middleware": AnalogGeneratedRouteRecord<"/docs/features/routing/middleware", "features/routing/middleware", "/docs/features/routing/middleware", "/docs", readonly []>;
  "/docs/features/routing/overview": AnalogGeneratedRouteRecord<"/docs/features/routing/overview", "features/routing/overview", "/docs/features/routing/overview", "/docs", readonly []>;
  "/docs/features/routing/typed-routes": AnalogGeneratedRouteRecord<"/docs/features/routing/typed-routes", "features/routing/typed-routes", "/docs/features/routing/typed-routes", "/docs", readonly []>;
  "/docs/features/server/server-side-rendering": AnalogGeneratedRouteRecord<"/docs/features/server/server-side-rendering", "features/server/server-side-rendering", "/docs/features/server/server-side-rendering", "/docs", readonly []>;
  "/docs/features/server/static-site-generation": AnalogGeneratedRouteRecord<"/docs/features/server/static-site-generation", "features/server/static-site-generation", "/docs/features/server/static-site-generation", "/docs", readonly []>;
  "/docs/features/testing/overview": AnalogGeneratedRouteRecord<"/docs/features/testing/overview", "features/testing/overview", "/docs/features/testing/overview", "/docs", readonly []>;
  "/docs/features/testing/vitest": AnalogGeneratedRouteRecord<"/docs/features/testing/vitest", "features/testing/vitest", "/docs/features/testing/vitest", "/docs", readonly []>;
  "/docs/features/updating/overview": AnalogGeneratedRouteRecord<"/docs/features/updating/overview", "features/updating/overview", "/docs/features/updating/overview", "/docs", readonly []>;
  "/docs/getting-started": AnalogGeneratedRouteRecord<"/docs/getting-started", "getting-started", "/docs/getting-started", "/docs", readonly []>;
  "/docs/guides/compatibility": AnalogGeneratedRouteRecord<"/docs/guides/compatibility", "guides/compatibility", "/docs/guides/compatibility", "/docs", readonly []>;
  "/docs/guides/forms": AnalogGeneratedRouteRecord<"/docs/guides/forms", "guides/forms", "/docs/guides/forms", "/docs", readonly []>;
  "/docs/guides/libraries": AnalogGeneratedRouteRecord<"/docs/guides/libraries", "guides/libraries", "/docs/guides/libraries", "/docs", readonly []>;
  "/docs/guides/migrating": AnalogGeneratedRouteRecord<"/docs/guides/migrating", "guides/migrating", "/docs/guides/migrating", "/docs", readonly []>;
  "/docs/integrations/angular-material/index": AnalogGeneratedRouteRecord<"/docs/integrations/angular-material/index", "integrations/angular-material", "/docs/integrations/angular-material", "/docs", readonly []>;
  "/docs/integrations/ionic/index": AnalogGeneratedRouteRecord<"/docs/integrations/ionic/index", "integrations/ionic", "/docs/integrations/ionic", "/docs", readonly []>;
  "/docs/integrations/nx/index": AnalogGeneratedRouteRecord<"/docs/integrations/nx/index", "integrations/nx", "/docs/integrations/nx", "/docs", readonly []>;
  "/docs/integrations/storybook/index": AnalogGeneratedRouteRecord<"/docs/integrations/storybook/index", "integrations/storybook", "/docs/integrations/storybook", "/docs", readonly []>;
  "/docs/integrations/tanstack-query/index": AnalogGeneratedRouteRecord<"/docs/integrations/tanstack-query/index", "integrations/tanstack-query", "/docs/integrations/tanstack-query", "/docs", readonly []>;
  "/docs/introduction": AnalogGeneratedRouteRecord<"/docs/introduction", "introduction", "/docs/introduction", "/docs", readonly []>;
  "/docs/packages/astro-angular/overview": AnalogGeneratedRouteRecord<"/docs/packages/astro-angular/overview", "packages/astro-angular/overview", "/docs/packages/astro-angular/overview", "/docs", readonly []>;
  "/docs/packages/create-analog/overview": AnalogGeneratedRouteRecord<"/docs/packages/create-analog/overview", "packages/create-analog/overview", "/docs/packages/create-analog/overview", "/docs", readonly []>;
  "/docs/packages/router/overview": AnalogGeneratedRouteRecord<"/docs/packages/router/overview", "packages/router/overview", "/docs/packages/router/overview", "/docs", readonly []>;
  "/docs/packages/vite-plugin-angular/css-preprocessors": AnalogGeneratedRouteRecord<"/docs/packages/vite-plugin-angular/css-preprocessors", "packages/vite-plugin-angular/css-preprocessors", "/docs/packages/vite-plugin-angular/css-preprocessors", "/docs", readonly []>;
  "/docs/packages/vite-plugin-angular/overview": AnalogGeneratedRouteRecord<"/docs/packages/vite-plugin-angular/overview", "packages/vite-plugin-angular/overview", "/docs/packages/vite-plugin-angular/overview", "/docs", readonly []>;
  "/docs/packages/vite-plugin-nitro/overview": AnalogGeneratedRouteRecord<"/docs/packages/vite-plugin-nitro/overview", "packages/vite-plugin-nitro/overview", "/docs/packages/vite-plugin-nitro/overview", "/docs", readonly []>;
  "/docs/sponsoring": AnalogGeneratedRouteRecord<"/docs/sponsoring", "sponsoring", "/docs/sponsoring", "/docs", readonly []>;
  "/docs/support": AnalogGeneratedRouteRecord<"/docs/support", "support", "/docs/support", "/docs", readonly []>;
  "/docs/[[...slug]]": AnalogGeneratedRouteRecord<"/docs/[[...slug]]", "[[...slug]]", "/docs/[[...slug]]", "/docs", readonly []>;
}

export interface AnalogFileRoutesByFullPath {
  "/": AnalogFileRoutesById["/index"];
  "/docs": AnalogFileRoutesById["/docs"];
  "/docs/contributing": AnalogFileRoutesById["/docs/contributing"];
  "/docs/contributors": AnalogFileRoutesById["/docs/contributors"];
  "/docs/features/api/og-image-generation": AnalogFileRoutesById["/docs/features/api/og-image-generation"];
  "/docs/features/api/overview": AnalogFileRoutesById["/docs/features/api/overview"];
  "/docs/features/api/websockets": AnalogFileRoutesById["/docs/features/api/websockets"];
  "/docs/features/data-fetching/overview": AnalogFileRoutesById["/docs/features/data-fetching/overview"];
  "/docs/features/data-fetching/server-side-data-fetching": AnalogFileRoutesById["/docs/features/data-fetching/server-side-data-fetching"];
  "/docs/features/data-fetching/validation": AnalogFileRoutesById["/docs/features/data-fetching/validation"];
  "/docs/features/deployment/overview": AnalogFileRoutesById["/docs/features/deployment/overview"];
  "/docs/features/deployment/providers": AnalogFileRoutesById["/docs/features/deployment/providers"];
  "/docs/features/generation/code-generation": AnalogFileRoutesById["/docs/features/generation/code-generation"];
  "/docs/features/routing/content": AnalogFileRoutesById["/docs/features/routing/content"];
  "/docs/features/routing/metadata": AnalogFileRoutesById["/docs/features/routing/metadata"];
  "/docs/features/routing/middleware": AnalogFileRoutesById["/docs/features/routing/middleware"];
  "/docs/features/routing/overview": AnalogFileRoutesById["/docs/features/routing/overview"];
  "/docs/features/routing/typed-routes": AnalogFileRoutesById["/docs/features/routing/typed-routes"];
  "/docs/features/server/server-side-rendering": AnalogFileRoutesById["/docs/features/server/server-side-rendering"];
  "/docs/features/server/static-site-generation": AnalogFileRoutesById["/docs/features/server/static-site-generation"];
  "/docs/features/testing/overview": AnalogFileRoutesById["/docs/features/testing/overview"];
  "/docs/features/testing/vitest": AnalogFileRoutesById["/docs/features/testing/vitest"];
  "/docs/features/updating/overview": AnalogFileRoutesById["/docs/features/updating/overview"];
  "/docs/getting-started": AnalogFileRoutesById["/docs/getting-started"];
  "/docs/guides/compatibility": AnalogFileRoutesById["/docs/guides/compatibility"];
  "/docs/guides/forms": AnalogFileRoutesById["/docs/guides/forms"];
  "/docs/guides/libraries": AnalogFileRoutesById["/docs/guides/libraries"];
  "/docs/guides/migrating": AnalogFileRoutesById["/docs/guides/migrating"];
  "/docs/integrations/angular-material": AnalogFileRoutesById["/docs/integrations/angular-material/index"];
  "/docs/integrations/ionic": AnalogFileRoutesById["/docs/integrations/ionic/index"];
  "/docs/integrations/nx": AnalogFileRoutesById["/docs/integrations/nx/index"];
  "/docs/integrations/storybook": AnalogFileRoutesById["/docs/integrations/storybook/index"];
  "/docs/integrations/tanstack-query": AnalogFileRoutesById["/docs/integrations/tanstack-query/index"];
  "/docs/introduction": AnalogFileRoutesById["/docs/introduction"];
  "/docs/packages/astro-angular/overview": AnalogFileRoutesById["/docs/packages/astro-angular/overview"];
  "/docs/packages/create-analog/overview": AnalogFileRoutesById["/docs/packages/create-analog/overview"];
  "/docs/packages/router/overview": AnalogFileRoutesById["/docs/packages/router/overview"];
  "/docs/packages/vite-plugin-angular/css-preprocessors": AnalogFileRoutesById["/docs/packages/vite-plugin-angular/css-preprocessors"];
  "/docs/packages/vite-plugin-angular/overview": AnalogFileRoutesById["/docs/packages/vite-plugin-angular/overview"];
  "/docs/packages/vite-plugin-nitro/overview": AnalogFileRoutesById["/docs/packages/vite-plugin-nitro/overview"];
  "/docs/sponsoring": AnalogFileRoutesById["/docs/sponsoring"];
  "/docs/support": AnalogFileRoutesById["/docs/support"];
  "/docs/[[...slug]]": AnalogFileRoutesById["/docs/[[...slug]]"];
}

export type AnalogRouteTreeId = keyof AnalogFileRoutesById;
export type AnalogRouteTreeFullPath = keyof AnalogFileRoutesByFullPath;

export const analogRouteTree = {
  byId: {
    "/index": {
      id: "/index",
      path: "/",
      fullPath: "/",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/index.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: true,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/index"],
    "/docs": {
      id: "/docs",
      path: "docs",
      fullPath: "/docs",
      parentId: null,
      children: ["/docs/contributing", "/docs/contributors", "/docs/features/api/og-image-generation", "/docs/features/api/overview", "/docs/features/api/websockets", "/docs/features/data-fetching/overview", "/docs/features/data-fetching/server-side-data-fetching", "/docs/features/data-fetching/validation", "/docs/features/deployment/overview", "/docs/features/deployment/providers", "/docs/features/generation/code-generation", "/docs/features/routing/content", "/docs/features/routing/metadata", "/docs/features/routing/middleware", "/docs/features/routing/overview", "/docs/features/routing/typed-routes", "/docs/features/server/server-side-rendering", "/docs/features/server/static-site-generation", "/docs/features/testing/overview", "/docs/features/testing/vitest", "/docs/features/updating/overview", "/docs/getting-started", "/docs/guides/compatibility", "/docs/guides/forms", "/docs/guides/libraries", "/docs/guides/migrating", "/docs/integrations/angular-material/index", "/docs/integrations/ionic/index", "/docs/integrations/nx/index", "/docs/integrations/storybook/index", "/docs/integrations/tanstack-query/index", "/docs/introduction", "/docs/packages/astro-angular/overview", "/docs/packages/create-analog/overview", "/docs/packages/router/overview", "/docs/packages/vite-plugin-angular/css-preprocessors", "/docs/packages/vite-plugin-angular/overview", "/docs/packages/vite-plugin-nitro/overview", "/docs/sponsoring", "/docs/support", "/docs/[[...slug]]"] as const,
      sourceFile: "/src/app/pages/docs.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: true,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs"],
    "/docs/contributing": {
      id: "/docs/contributing",
      path: "contributing",
      fullPath: "/docs/contributing",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/contributing.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/contributing"],
    "/docs/contributors": {
      id: "/docs/contributors",
      path: "contributors",
      fullPath: "/docs/contributors",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/contributors.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/contributors"],
    "/docs/features/api/og-image-generation": {
      id: "/docs/features/api/og-image-generation",
      path: "features/api/og-image-generation",
      fullPath: "/docs/features/api/og-image-generation",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/features/api/og-image-generation.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/features/api/og-image-generation"],
    "/docs/features/api/overview": {
      id: "/docs/features/api/overview",
      path: "features/api/overview",
      fullPath: "/docs/features/api/overview",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/features/api/overview.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/features/api/overview"],
    "/docs/features/api/websockets": {
      id: "/docs/features/api/websockets",
      path: "features/api/websockets",
      fullPath: "/docs/features/api/websockets",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/features/api/websockets.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/features/api/websockets"],
    "/docs/features/data-fetching/overview": {
      id: "/docs/features/data-fetching/overview",
      path: "features/data-fetching/overview",
      fullPath: "/docs/features/data-fetching/overview",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/features/data-fetching/overview.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/features/data-fetching/overview"],
    "/docs/features/data-fetching/server-side-data-fetching": {
      id: "/docs/features/data-fetching/server-side-data-fetching",
      path: "features/data-fetching/server-side-data-fetching",
      fullPath: "/docs/features/data-fetching/server-side-data-fetching",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/features/data-fetching/server-side-data-fetching.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/features/data-fetching/server-side-data-fetching"],
    "/docs/features/data-fetching/validation": {
      id: "/docs/features/data-fetching/validation",
      path: "features/data-fetching/validation",
      fullPath: "/docs/features/data-fetching/validation",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/features/data-fetching/validation.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/features/data-fetching/validation"],
    "/docs/features/deployment/overview": {
      id: "/docs/features/deployment/overview",
      path: "features/deployment/overview",
      fullPath: "/docs/features/deployment/overview",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/features/deployment/overview.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/features/deployment/overview"],
    "/docs/features/deployment/providers": {
      id: "/docs/features/deployment/providers",
      path: "features/deployment/providers",
      fullPath: "/docs/features/deployment/providers",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/features/deployment/providers.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/features/deployment/providers"],
    "/docs/features/generation/code-generation": {
      id: "/docs/features/generation/code-generation",
      path: "features/generation/code-generation",
      fullPath: "/docs/features/generation/code-generation",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/features/generation/code-generation.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/features/generation/code-generation"],
    "/docs/features/routing/content": {
      id: "/docs/features/routing/content",
      path: "features/routing/content",
      fullPath: "/docs/features/routing/content",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/features/routing/content.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/features/routing/content"],
    "/docs/features/routing/metadata": {
      id: "/docs/features/routing/metadata",
      path: "features/routing/metadata",
      fullPath: "/docs/features/routing/metadata",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/features/routing/metadata.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/features/routing/metadata"],
    "/docs/features/routing/middleware": {
      id: "/docs/features/routing/middleware",
      path: "features/routing/middleware",
      fullPath: "/docs/features/routing/middleware",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/features/routing/middleware.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/features/routing/middleware"],
    "/docs/features/routing/overview": {
      id: "/docs/features/routing/overview",
      path: "features/routing/overview",
      fullPath: "/docs/features/routing/overview",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/features/routing/overview.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/features/routing/overview"],
    "/docs/features/routing/typed-routes": {
      id: "/docs/features/routing/typed-routes",
      path: "features/routing/typed-routes",
      fullPath: "/docs/features/routing/typed-routes",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/features/routing/typed-routes.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/features/routing/typed-routes"],
    "/docs/features/server/server-side-rendering": {
      id: "/docs/features/server/server-side-rendering",
      path: "features/server/server-side-rendering",
      fullPath: "/docs/features/server/server-side-rendering",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/features/server/server-side-rendering.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/features/server/server-side-rendering"],
    "/docs/features/server/static-site-generation": {
      id: "/docs/features/server/static-site-generation",
      path: "features/server/static-site-generation",
      fullPath: "/docs/features/server/static-site-generation",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/features/server/static-site-generation.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/features/server/static-site-generation"],
    "/docs/features/testing/overview": {
      id: "/docs/features/testing/overview",
      path: "features/testing/overview",
      fullPath: "/docs/features/testing/overview",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/features/testing/overview.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/features/testing/overview"],
    "/docs/features/testing/vitest": {
      id: "/docs/features/testing/vitest",
      path: "features/testing/vitest",
      fullPath: "/docs/features/testing/vitest",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/features/testing/vitest.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/features/testing/vitest"],
    "/docs/features/updating/overview": {
      id: "/docs/features/updating/overview",
      path: "features/updating/overview",
      fullPath: "/docs/features/updating/overview",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/features/updating/overview.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/features/updating/overview"],
    "/docs/getting-started": {
      id: "/docs/getting-started",
      path: "getting-started",
      fullPath: "/docs/getting-started",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/getting-started.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/getting-started"],
    "/docs/guides/compatibility": {
      id: "/docs/guides/compatibility",
      path: "guides/compatibility",
      fullPath: "/docs/guides/compatibility",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/guides/compatibility.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/guides/compatibility"],
    "/docs/guides/forms": {
      id: "/docs/guides/forms",
      path: "guides/forms",
      fullPath: "/docs/guides/forms",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/guides/forms.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/guides/forms"],
    "/docs/guides/libraries": {
      id: "/docs/guides/libraries",
      path: "guides/libraries",
      fullPath: "/docs/guides/libraries",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/guides/libraries.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/guides/libraries"],
    "/docs/guides/migrating": {
      id: "/docs/guides/migrating",
      path: "guides/migrating",
      fullPath: "/docs/guides/migrating",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/guides/migrating.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/guides/migrating"],
    "/docs/integrations/angular-material/index": {
      id: "/docs/integrations/angular-material/index",
      path: "integrations/angular-material",
      fullPath: "/docs/integrations/angular-material",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/integrations/angular-material/index.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: true,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/integrations/angular-material/index"],
    "/docs/integrations/ionic/index": {
      id: "/docs/integrations/ionic/index",
      path: "integrations/ionic",
      fullPath: "/docs/integrations/ionic",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/integrations/ionic/index.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: true,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/integrations/ionic/index"],
    "/docs/integrations/nx/index": {
      id: "/docs/integrations/nx/index",
      path: "integrations/nx",
      fullPath: "/docs/integrations/nx",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/integrations/nx/index.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: true,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/integrations/nx/index"],
    "/docs/integrations/storybook/index": {
      id: "/docs/integrations/storybook/index",
      path: "integrations/storybook",
      fullPath: "/docs/integrations/storybook",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/integrations/storybook/index.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: true,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/integrations/storybook/index"],
    "/docs/integrations/tanstack-query/index": {
      id: "/docs/integrations/tanstack-query/index",
      path: "integrations/tanstack-query",
      fullPath: "/docs/integrations/tanstack-query",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/integrations/tanstack-query/index.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: true,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/integrations/tanstack-query/index"],
    "/docs/introduction": {
      id: "/docs/introduction",
      path: "introduction",
      fullPath: "/docs/introduction",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/introduction.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/introduction"],
    "/docs/packages/astro-angular/overview": {
      id: "/docs/packages/astro-angular/overview",
      path: "packages/astro-angular/overview",
      fullPath: "/docs/packages/astro-angular/overview",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/packages/astro-angular/overview.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/packages/astro-angular/overview"],
    "/docs/packages/create-analog/overview": {
      id: "/docs/packages/create-analog/overview",
      path: "packages/create-analog/overview",
      fullPath: "/docs/packages/create-analog/overview",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/packages/create-analog/overview.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/packages/create-analog/overview"],
    "/docs/packages/router/overview": {
      id: "/docs/packages/router/overview",
      path: "packages/router/overview",
      fullPath: "/docs/packages/router/overview",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/packages/router/overview.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/packages/router/overview"],
    "/docs/packages/vite-plugin-angular/css-preprocessors": {
      id: "/docs/packages/vite-plugin-angular/css-preprocessors",
      path: "packages/vite-plugin-angular/css-preprocessors",
      fullPath: "/docs/packages/vite-plugin-angular/css-preprocessors",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/packages/vite-plugin-angular/css-preprocessors.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/packages/vite-plugin-angular/css-preprocessors"],
    "/docs/packages/vite-plugin-angular/overview": {
      id: "/docs/packages/vite-plugin-angular/overview",
      path: "packages/vite-plugin-angular/overview",
      fullPath: "/docs/packages/vite-plugin-angular/overview",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/packages/vite-plugin-angular/overview.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/packages/vite-plugin-angular/overview"],
    "/docs/packages/vite-plugin-nitro/overview": {
      id: "/docs/packages/vite-plugin-nitro/overview",
      path: "packages/vite-plugin-nitro/overview",
      fullPath: "/docs/packages/vite-plugin-nitro/overview",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/packages/vite-plugin-nitro/overview.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/packages/vite-plugin-nitro/overview"],
    "/docs/sponsoring": {
      id: "/docs/sponsoring",
      path: "sponsoring",
      fullPath: "/docs/sponsoring",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/sponsoring.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/sponsoring"],
    "/docs/support": {
      id: "/docs/support",
      path: "support",
      fullPath: "/docs/support",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/support.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/support"],
    "/docs/[[...slug]]": {
      id: "/docs/[[...slug]]",
      path: "[[...slug]]",
      fullPath: "/docs/[[...slug]]",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/app/pages/docs/[[...slug]].page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: true,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: true,
    } satisfies AnalogFileRoutesById["/docs/[[...slug]]"],
  },
  byFullPath: {
    "/": "/index",
    "/docs": "/docs",
    "/docs/contributing": "/docs/contributing",
    "/docs/contributors": "/docs/contributors",
    "/docs/features/api/og-image-generation": "/docs/features/api/og-image-generation",
    "/docs/features/api/overview": "/docs/features/api/overview",
    "/docs/features/api/websockets": "/docs/features/api/websockets",
    "/docs/features/data-fetching/overview": "/docs/features/data-fetching/overview",
    "/docs/features/data-fetching/server-side-data-fetching": "/docs/features/data-fetching/server-side-data-fetching",
    "/docs/features/data-fetching/validation": "/docs/features/data-fetching/validation",
    "/docs/features/deployment/overview": "/docs/features/deployment/overview",
    "/docs/features/deployment/providers": "/docs/features/deployment/providers",
    "/docs/features/generation/code-generation": "/docs/features/generation/code-generation",
    "/docs/features/routing/content": "/docs/features/routing/content",
    "/docs/features/routing/metadata": "/docs/features/routing/metadata",
    "/docs/features/routing/middleware": "/docs/features/routing/middleware",
    "/docs/features/routing/overview": "/docs/features/routing/overview",
    "/docs/features/routing/typed-routes": "/docs/features/routing/typed-routes",
    "/docs/features/server/server-side-rendering": "/docs/features/server/server-side-rendering",
    "/docs/features/server/static-site-generation": "/docs/features/server/static-site-generation",
    "/docs/features/testing/overview": "/docs/features/testing/overview",
    "/docs/features/testing/vitest": "/docs/features/testing/vitest",
    "/docs/features/updating/overview": "/docs/features/updating/overview",
    "/docs/getting-started": "/docs/getting-started",
    "/docs/guides/compatibility": "/docs/guides/compatibility",
    "/docs/guides/forms": "/docs/guides/forms",
    "/docs/guides/libraries": "/docs/guides/libraries",
    "/docs/guides/migrating": "/docs/guides/migrating",
    "/docs/integrations/angular-material": "/docs/integrations/angular-material/index",
    "/docs/integrations/ionic": "/docs/integrations/ionic/index",
    "/docs/integrations/nx": "/docs/integrations/nx/index",
    "/docs/integrations/storybook": "/docs/integrations/storybook/index",
    "/docs/integrations/tanstack-query": "/docs/integrations/tanstack-query/index",
    "/docs/introduction": "/docs/introduction",
    "/docs/packages/astro-angular/overview": "/docs/packages/astro-angular/overview",
    "/docs/packages/create-analog/overview": "/docs/packages/create-analog/overview",
    "/docs/packages/router/overview": "/docs/packages/router/overview",
    "/docs/packages/vite-plugin-angular/css-preprocessors": "/docs/packages/vite-plugin-angular/css-preprocessors",
    "/docs/packages/vite-plugin-angular/overview": "/docs/packages/vite-plugin-angular/overview",
    "/docs/packages/vite-plugin-nitro/overview": "/docs/packages/vite-plugin-nitro/overview",
    "/docs/sponsoring": "/docs/sponsoring",
    "/docs/support": "/docs/support",
    "/docs/[[...slug]]": "/docs/[[...slug]]",
  },
} as const;

export type AnalogJsonLdDocument = WithContext<Thing> | Graph | Array<WithContext<Thing>>;
export type GeneratedJsonLdManifestEntry = { routePath: string; sourceFile: string; kind: 'module' | 'content'; resolveJsonLd: () => AnalogJsonLdDocument[]; };

function normalizeJsonLd(value: unknown): AnalogJsonLdDocument[] {
  if (Array.isArray(value)) {
    return value.filter((entry): entry is AnalogJsonLdDocument => typeof entry === 'object' && entry !== null && !Array.isArray(entry));
  }

  return typeof value === 'object' && value !== null ? [value as AnalogJsonLdDocument] : [];
}

function resolveModuleJsonLd(routeModule: unknown): AnalogJsonLdDocument[] {
  const typedRouteModule = routeModule as { routeJsonLd?: unknown; routeMeta?: { jsonLd?: unknown } };
  return normalizeJsonLd(typedRouteModule.routeMeta?.jsonLd ?? typedRouteModule.routeJsonLd);
}

export const routeJsonLdManifest = new Map<string, GeneratedJsonLdManifestEntry>([
  ['/docs', { routePath: '/docs', sourceFile: '/src/app/pages/docs.page.ts', kind: 'module', resolveJsonLd: () => resolveModuleJsonLd(routeModule0) }],
  ['/docs/[[...slug]]', { routePath: '/docs/[[...slug]]', sourceFile: '/src/app/pages/docs/[[...slug]].page.ts', kind: 'module', resolveJsonLd: () => resolveModuleJsonLd(routeModule1) }],
]);
